TRUTH_STRINGS = (
   "What’s the last lie you told?",
   "What was the most embarrassing thing you’ve ever done on a date?",
   "Have you ever accidentally hit something (or someone!) with your car?",
   "Name someone you’ve pretended to like but actually couldn’t stand.",
   "What’s your most bizarre nickname?",
   "What’s been your most physically painful experience?",
   "What bridges are you glad that you burned?",
   "What’s the craziest thing you’ve done on public transportation?",
   "If you met a genie, what would your three wishes be?",
   "If you could write anyone on Earth in for President of the United States, who would it be and why?",
   "What’s the meanest thing you’ve ever said to someone else?",
   "Who was your worst kiss ever?",
   "What’s one thing you’d do if you knew there no consequences?",
   "What’s the craziest thing you’ve done in front of a mirror?",
   "What’s the meanest thing you’ve ever said about someone else?",
   "What’s something you love to do with your friends that you’d never do in front of your partner?",
   "Who are you most jealous of?",
   "What do your favorite pajamas look like?",
   "Have you ever faked sick to get out of a party?",
   "Who’s the oldest person you’ve dated?",
   "How many selfies do you take a day?",
   "Meatloaf says he’d do anything for love, but he won’t do “that.” What’s your “that?”",
   "How many times a week do you wear the same pants?",
   "Would you date your high school crush today?",
   "Where are you ticklish?",
   "Do you believe in any superstitions? If so, which ones?",
   "What’s one movie you’re embarrassed to admit you enjoy?",
   "What’s your most embarrassing grooming habit?",
   "When’s the last time you apologized? What for?",
   "How do you really feel about the Twilight saga?",
   "Where do most of your embarrassing odors come from?",
   "Have you ever considered cheating on a partner?",
   "Have you ever cheated on a partner?",
   "Boxers or briefs?",
   "Have you ever peed in a pool?",
   "What’s the weirdest place you’ve ever grown hair?",
   "If you were guaranteed to never get caught, who on Earth would you murder?",
   "What’s the cheapest gift you’ve ever gotten for someone else?",
   "What app do you waste the most time on?",
   "What’s the weirdest thing you’ve done on a plane?",
   "Have you ever been nude in public?",
   "How many gossip blogs do you read a day?",
   "What is the youngest age partner you’d date?",
   "Have you ever picked your nose in public?",
   "Have you ever lied about your age?",
   "If you had to delete one app from your phone, which one would it be?",
   "What’s your most embarrassing late night purchase?",
   "What’s the longest you’ve gone without showering?",
   "Have you ever used a fake ID?",
   "Who’s your hall pass?",
   "Be honest: Do you have a favorite child?", 
   "Which of your family members annoys you the most and why?", 
   "What is your greatest fear in a relationship?", 
   "What’s your biggest pet peeve about the person to your left?", 
   "What’s the most embarrassing text in your phone right now?", 
   "Have you ever seen a dead body?", 
   "What celebrity do you think is overrated?", 
   "Have you ever lied to your boss?", 
   "Have you ever stolen something from work?", 
   "What’s the longest you’ve gone without brushing your teeth?", 
   "What’s your biggest regret in life?", 
   "Who would you hate to see naked?", 
   "Describe the weirdest thing you’ve ever done while inebriated.", 
   "Have you ever regifted a present?", 
   "Would you break up with your partner for $1 million?", 
   "Have you ever had a crush on a coworker?", 
   "Do you still have feelings for any of your exes?", 
   "What’s the smallest tip you’ve ever left at a restaurant?", 
   "Have you ever regretted something you did to get a crush or partner’s attention?", 
   "What’s one job you could never do?", 
   "Have you ever ghosted a friend?", 
   "Have you ever ghosted a partner?", 
   "What’s the most scandalous photo in your cloud?", 
   "If you switched genders for a day, what would you do?", 
   "How many photo editing apps do you have on your phone?", 
   "How many pairs of granny panties do you own?", 
   "What are your favorite and least favorite of your body parts?", 
   "When’s the last time you got dumped?", 
   "What’s the most childish thing you still do?", 
   "When’s the last time you dumped someone?", 
   "If you had to pick someone in this room to be your partner on a game show, who would it be and why?", 
   "Would you date someone shorter than you?", 
   "Have you ever lied for a friend?", 
   "Name one thing you’d change about every person in this room.", 
   "When’s the last time you made someone else cry?", 
   "What’s the most embarrassing thing you’ve done in front of a crowd?", 
   "If you could become invisible, what’s the worst thing you’d do?", 
   "After you’ve dropped a piece of food, what’s the longest time you’ve left it on the floor before eating it?", 
   "What’s one thing in your life you wish you could change?", 
   "If you could date two people at once, would you do it? If so, who?", 
   "What’s something that overwhelms you?", 
   "What was the greatest day of your life?", 
   "What’s one useless skill you’d love to learn anyway?", 
   "If I went through your cabinets, what’s the weirdest thing I’d find?", 
   "Have you ever farted and blamed it on someone else?", 
   "What’s the worst thing you’ve ever done at work?", 
   "How many people have you kissed?", 
   "What’s your number?", 
   "Have you ever gotten mad at a friend for posting an unflattering picture of you?", 
   "What’s your most absurd dealbreaker?", 
   "Who in this room would you list as your emergency contact?", 
   "What’s something you would die if your mom found out about?", 
   "What’s the scariest thing that’s ever happened to you?", 
   "If you could set anyone here up with your best friend, who would it be and why?", 
   "How often do you wash your sheets?", 
   "Have you ever farted in an elevator?", 
   "Who was your first love?", 
   "What’s the last purchase you regretted?", 
   "Have you ever sent a sext?", 
   "Have you ever sent a sext to the wrong person? Who?", 
   "What’s the weirdest dream you’ve ever had?", 
   "Have you ever had a one-night stand?", 
   "Are you scared of getting old?", 
   "What do you want on your tombstone?", 
   "If you had one week to live and you had to marry someone in this room, who would it be?", 
   "What’s the last movie that made you cry?", 
   "List one positive and one negative thing about everyone in the room.", 
   "When was your first time?", 
   "Who was your first?", 
   "What’s the most sinful thing you’ve done in a house of worship?", 
   "Who would you call to help bury a body?", 
   "Who would call you to help bury a body? Would you do it?", 
   "When’s the last time you cried and why?", 
   "What’s your favorite possession?", 
   "Has anyone ever walked in on you in the bathroom?", 
   "Who in this group would you want to swap lives with for a week?", 
   "What was your biggest fear as a child?", 
   "What’s your biggest fear today?", 
   "What’s the most embarrassing thing your parents have caught you doing?", 
   "Name a band you only pretend to like.", 
   "What’s the last song that made you cry?", 
   "Have you ever had a wardrobe malfunction?", 
   "What’s the last thing you Googled?", 
   "What is that one thing you would never do for all the money in the world?", 
   "Who is your favorite person in your immediate family?", 
   "If you could only hear one song for the rest of your life, what would it be?", 
   "When’s the last time your partner embarrassed you?",  
)



DARE_STRINGS = (
   "Change your profile pic to some naked character for 3 days.",
   "Do a photograph reveal.",
   "Share your telegram password.",
   "Send 'I Love You' to 20 people in your PM [Private Messaging] list and share screenshots of the task.",
   "Send hentai to 10 people in your PM [Private Messaging list and share screenshots of the task.",
   "Send your phone number to 10 people in the group and share screenshots of the task.",
   "Share your every social media account username.",
   "Send most embarrising photograph.",
   "Send 'I want your nudes' to 10 people in your PM [Private Messaging list and share screenshots of the task.]",
   "Make your phone number public for 3 minutes.",
   "Set your bio as, 'I am gay and I want to sleep with the person reading this right now' for 2 days.", 
   "Send the pictures of your ex's panties.",
   "Ask for nudes from strangers and share screenshots of the task.",
   "Share screenshot from most recent chat on WhatsApp.",
   "Join/Start Voice Chat and sing a song.",
   "Join/Start Voice Chat and say, 'Ara Ara', in sexy voice",
   "Go to a random group with its Voice Chat ongoing and members speaking. Join the group and shout 'Fuck you all'. [Screen Record the task and send it in group.]",
   "Go to a random group with its Voice Chat ongoing and members speaking. Join the group and seduce a person. [Screen Record the task and send it in group.]",
   "Download a nude pic using google, PM it to a member of random Anime themed Group with caption as, 'These nudes are mine, wanna share yours?'. [Share screenshots of the task.]",
   "Open the top most chat on your PM List and screen record chat for last 3 days and send it in group.",
   "Reveal your instagram password to someone who is online.",
   "Click a photo of yours right now and send it in group.",
   "Set your bio as, 'Free blowjob if you send your nudes.' for 2 days.",
   "Join/Start Voice Chat and say, 'Onii Chan no Hentai', in voice.",
   "Let someone from the players log in to your Telegram account.",
   "Send 10 most recent images from your galary.",
)
